### ISSUE TITLE
Removal of external dependencies

### ISSUE THREAD

**Issue by Dirzei** [gbenroscience/ParserNG#6]
Hi,

another request. Is it possible to remove the dependencies to "com.google.gson.Gson".

Thank you - cheers
Dirk

**Comment by gbenroscience** [comment]
Hi Dirk,
Why would you want to do that, please?

**Comment by Dirzei** [comment]
Hi Jiboye,

I think than you have a nice and clean library without external dependencies.
Some people (inlcuding me) potential like this. (I have already removed it, but I have done it Kind of quick and dirty, and did not get the full Background of the dependency?)
May there is a way to move the dependency to some Kind off add on class or lib?
If anyone runs your lib in an application this dependency might not wanted at all?

What do you think?

Cheers
Dirk

Gesendet von Mail für Windows 10

Von: Gbemiro Jiboye
Gesendet: Donnerstag, 7. Januar 2021 11:22
An: gbenroscience/ParserNG
Cc: Dirzei; Author
Betreff: Re: [gbenroscience/ParserNG] Removal of external dependencies (#6)

Hi Dirk,
Why would you want to do that, please?

**Comment by gbenroscience** [comment]
Hi Dirzei,

Fair enough.
I introduced the dependency a while back. But the purpose is no longer a valid one.

I will remove it and leave the library as standalone.

**EDIT**

I took a look at the codebase and realised that this is not a trivial task.
ParserNG uses Gson as a quick serializer/deserializer for objects of some core classes for apps that might need to persist state(to the filesystem).

I will add this to a long term list of things and write a simple serializer/deserializer if needed so that the library wont need that dependency.

For now, Gson will still be a part of the library's dependecies

**Comment by Dirzei** [comment]
Thank you very much.

After my test and your changes / additions I want to use your library in my project.

Cheers
Dirk

Gesendet von Mail für Windows 10

Von: Gbemiro Jiboye
Gesendet: Donnerstag, 7. Januar 2021 13:41
An: gbenroscience/ParserNG
Cc: Dirzei; Author
Betreff: Re: [gbenroscience/ParserNG] Removal of external dependencies (#6)

Hi Dirzei,
Fair enough.
I introduced the dependency a while back. But the purpose is no longer a valid one.
I will remove it and leave the library as standalone.

**Comment by gbenroscience** [comment]
Hi Dirk,

I have written a native serializer using Java serialization. 
I have removed Gson from the library.
It has no external dependency again.

Thanks for the vote of confidence.

**Comment by Dirzei** [comment]
Thank you very much! I will download you latest Version. CheersDirkVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------
Hi Dirk,
I have written a native serializer using Java serialization.
I have removed Gson from the library.
It has no external dependency again.
Thanks for the vote of confidence.
